from PreProsses import PreProcess
from Model import ModelCreator


# train, target = PreProcess('Tehran').process_input_data()
# print(train)
# model = ModelCreator(train, target, test_split_available=True, test_size=0.5, estimator='randomForest', estimators=['tree', 'knn', 'linear', 'randomForest'])
# model.train_model('svr')
# model.train_model('logistic')
# model.train_model('tree')
# model.train_model('linear')
# model.train_model('knn')
# model.train_model('lasso')
# model.train_model('ridge')
# model.train_model('bayesian')
# model.train_model('tree')
# model.train_model('bagging')
# model.train_model('voting')
# print()
# print()


train, target = PreProcess('Ghom').process_input_data(drop=False)
model = ModelCreator(train, target, test_split_available=True, test_size=0.2, estimator='randomForest', estimators=['tree', 'bayesian', 'linear', 'randomForest'])
model.train_model('linear')
model.train_model('bagging')
model.train_model('voting')
# model.train_model('ElasticNet')
# model.train_model('TheilSenRegressor')
# model.train_model('ARDRegression')
# model.train_model('RANSACRegressor')
# model.train_model('HuberRegressor')

# train, target = PreProcess('Travel_data.xlsx').process_input_data()
# model = ModelCreator(train, target, test_split_available=True, test_size=0.2)
# model.train_model('logistic')
# model.train_model('tree')
# model.train_model('linear')
# model.train_model('knn')
# model.train_model('lasso')
# model.train_model('bayesian')
# model.train_model('ridge')
# print()
# print()

# train, target = PreProcess('Travel_data_full_column.xlsx').process_input_data()
# model = ModelCreator(train, target)
# model.train_model('logistic')
# model.train_model('tree')
# model.train_model('linear')
# model.train_model('knn')
# model.train_model('lasso')
# model.train_model('ridge')
# model.train_model('bayesian')
# print()
# print()

# train, target = PreProcess('Travel_data_full_column.xlsx').process_input_data()
# model = ModelCreator(train, target, test_split_available=True, test_size=0.2)
# model.train_model('svr', plot_input=True)
# model.train_model('logistic')
# model.train_model('tree')
# model.train_model('linear')
# model.train_model('knn')
# model.train_model('lasso')
# model.train_model('lassolars')
# model.train_model('bayesian')
# model.train_model('ridge')
# model.train_model('ridgecv')
# model.train_model('ElasticNet')
# model.train_model('TheilSenRegressor')
# model.train_model('ARDRegression')
# model.train_model('RANSACRegressor')
# model.train_model('HuberRegressor')
# print()
# print()